name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: make build

    - name: Copy Files
      run: |
           mkdir  artifacts
           cp api artifacts/.

    - name: Archive
      uses: actions/upload-artifact@v2
      with:
          name: api
          path: artifacts

